upstream app_servers {
    server app1:8000;
    server app2:8000;
    server app3:8000;
}

server {
    listen 80;
    client_max_body_size 10m;

    location /media/ {
        proxy_pass http://minio:9000/product-images/;
    }

    location / {
        proxy_pass http://app_servers;
    }
}