"""Протоколы репозиториев — контракт слоя доступа к данным.

Сервисы и API зависят от этих протоколов, а не от конкретной реализации (SQL/ORM).
Реализацию можно заменить (например, на ORM) без изменения кода выше по стеку.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from shop.app.models.domain.product_image import ProductImageCreateData
from shop.app.models.schemas import CartItemOut
from shop.app.models.schemas import CartOut
from shop.app.models.schemas import CategoryOut
from shop.app.models.schemas import EventLogOut
from shop.app.models.schemas import OrderItemOut
from shop.app.models.schemas import OrderOut
from shop.app.models.schemas import ProductImageOut
from shop.app.models.schemas import ProductOut
from shop.app.models.schemas import ProductSpecificationOut
from shop.app.models.schemas import RefreshTokenOut
from shop.app.models.schemas import ReviewOut
from shop.app.models.schemas import RoleOut
from shop.app.models.schemas import UserDB, UserOut


class CategoryRepository(Protocol):
    async def get_by_id(self, category_id: int) -> CategoryOut | None: ...
    async def get_all(self) -> list[CategoryOut]: ...
    async def create(self, category_data: dict) -> int: ...
    async def update(self, category_id: int, update_data: dict) -> bool: ...
    async def delete(self, category_id: int) -> bool: ...
    async def exists_category_with_id(self, category_id: int) -> bool: ...
    async def exists_category_with_name(self, category_name: str) -> bool: ...


class ProductRepository(Protocol):
    async def get_by_id(self, product_id: int) -> ProductOut | None: ...
    async def get_all(self, limit: int, offset: int) -> list[ProductOut]: ...
    async def get_total(self) -> int: ...
    async def create(self, product_data: dict) -> int: ...
    async def update(self, product_id: int, update_data: dict) -> bool: ...
    async def delete(self, product_id: int) -> bool: ...
    async def exists_product_with_id(self, product_id: int) -> bool: ...


class UserRepository(Protocol):
    async def get_all(self, limit: int, offset: int) -> list[UserOut]: ...
    async def get_total(self) -> int: ...
    async def get_by_id(self, user_id: int) -> UserOut | None: ...
    async def get_by_username(self, username: str) -> UserDB | None: ...
    async def create(self, user_data: dict) -> int: ...
    async def update(self, user_id: int, update_data: dict) -> bool: ...
    async def update_last_login(
        self, user_id: int, last_login: datetime | None = None
    ) -> bool: ...
    async def delete(self, user_id: int) -> bool: ...
    async def exists_with_username(self, username: str) -> bool: ...
    async def exists_with_email(self, email: str) -> bool: ...


class RoleRepository(Protocol):
    async def get_all(self) -> list[RoleOut]: ...
    async def get_by_id(self, role_id: int) -> RoleOut | None: ...
    async def get_by_name(self, name: str) -> RoleOut | None: ...
    async def create(self, name: str) -> int: ...
    async def update(self, role_id: int, name: str) -> bool: ...
    async def delete(self, role_id: int) -> bool: ...
    async def exists_with_name(self, name: str) -> bool: ...


class ProductSpecificationRepository(Protocol):
    async def get_all(self) -> list[ProductSpecificationOut]: ...
    async def get_by_id(
        self, specification_id: int
    ) -> ProductSpecificationOut | None: ...
    async def get_by_product_id(
        self, product_id: int
    ) -> ProductSpecificationOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, specification_id: int, data: dict) -> bool: ...
    async def delete(self, specification_id: int) -> bool: ...


class ProductImageRepository(Protocol):
    async def get_by_product_id(self, product_id: int) -> list[ProductImageOut]: ...
    async def get_by_id(self, image_id: int) -> ProductImageOut | None: ...
    async def create(self, product: ProductImageCreateData) -> int: ...
    async def update(self, image_id: int, data: dict) -> bool: ...
    async def delete(self, image_id: int) -> bool: ...
    async def delete_by_product_id(self, product_id: int) -> list[int]: ...


class CartRepository(Protocol):
    async def get_all(self, limit: int, offset: int) -> list[CartOut]: ...
    async def get_by_id(self, cart_id: int) -> CartOut | None: ...
    async def get_by_user_id(self, user_id: int) -> CartOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, cart_id: int, data: dict) -> bool: ...
    async def delete(self, cart_id: int) -> bool: ...


class CartItemRepository(Protocol):
    async def get_by_cart_id(self, cart_id: int) -> list[CartItemOut]: ...
    async def get_by_id(self, item_id: int) -> CartItemOut | None: ...
    async def get_by_cart_and_product(
        self, cart_id: int, product_id: int
    ) -> CartItemOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, item_id: int, data: dict) -> bool: ...
    async def delete(self, item_id: int) -> bool: ...
    async def delete_by_cart_id(self, cart_id: int) -> list[int]: ...


class ReviewRepository(Protocol):
    async def get_all(self, limit: int, offset: int) -> list[ReviewOut]: ...
    async def get_by_id(self, review_id: int) -> ReviewOut | None: ...
    async def get_by_user_and_product(
        self, user_id: int, product_id: int
    ) -> ReviewOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, review_id: int, data: dict) -> bool: ...
    async def delete(self, review_id: int) -> bool: ...


class OrderRepository(Protocol):
    async def get_all(self, limit: int, offset: int) -> list[OrderOut]: ...
    async def get_total(self) -> int: ...
    async def get_by_id(self, order_id: int) -> OrderOut | None: ...
    async def get_by_number(self, order_number: str) -> OrderOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, order_id: int, data: dict) -> bool: ...
    async def delete(self, order_id: int) -> bool: ...


class OrderItemRepository(Protocol):
    async def get_by_order_id(self, order_id: int) -> list[OrderItemOut]: ...
    async def get_by_id(self, item_id: int) -> OrderItemOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def update(self, item_id: int, data: dict) -> bool: ...
    async def delete(self, item_id: int) -> bool: ...
    async def delete_by_order_id(self, order_id: int) -> list[int]: ...


class EventLogRepository(Protocol):
    async def get_all(self, limit: int, offset: int) -> list[EventLogOut]: ...
    async def get_by_id(self, event_id: int) -> EventLogOut | None: ...
    async def get_by_user_id(
        self, user_id: int, limit: int, offset: int
    ) -> list[EventLogOut]: ...
    async def get_filtered(
        self,
        *,
        time_from: datetime | None = None,
        time_to: datetime | None = None,
        user_id: int | None = None,
        event_type: str | None = None,
        limit: int,
        offset: int,
    ) -> tuple[list[EventLogOut], int]: ...
    async def create(self, data: dict) -> int: ...
    async def delete(self, event_id: int) -> bool: ...


class RefreshTokenRepository(Protocol):
    async def get_by_user_id(self, user_id: int) -> list[RefreshTokenOut]: ...
    async def get_by_hash(self, token_hash: str) -> RefreshTokenOut | None: ...
    async def create(self, data: dict) -> int: ...
    async def delete(self, token_id: int) -> bool: ...
    async def delete_by_hash(self, token_hash: str) -> list[int]: ...
    async def delete_by_user_id(self, user_id: int) -> list[int]: ...


class UnitOfWork(Protocol):
    categories: CategoryRepository
    products: ProductRepository
    users: UserRepository
    roles: RoleRepository
    product_specifications: ProductSpecificationRepository
    product_images: ProductImageRepository
    carts: CartRepository
    cart_items: CartItemRepository
    reviews: ReviewRepository
    orders: OrderRepository
    order_items: OrderItemRepository
    refresh_tokens: RefreshTokenRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class EventLogAnalyticsRepository(Protocol):
    async def aggregate_activity_by_period(
        self,
        period: str,
        time_from: datetime | None = None,
        time_to: datetime | None = None,
    ) -> list[dict]: ...
    async def aggregate_top_users(self, limit: int = 10) -> list[dict]: ...
    async def aggregate_event_type_stats(self) -> list[dict]: ...
    async def aggregate_time_series(
        self,
        time_from: datetime,
        time_to: datetime,
        granularity: str = "hour",
    ) -> list[dict]: ...
    async def aggregate_user_anomalies(
        self,
        time_from: datetime,
        std_threshold: float = 2.0,
    ) -> list[dict]: ...


class S3ServiceProtocol(Protocol):
    async def upload_object(
        self,
        object_name: str,
        content: bytes,
        content_type: str | None = None,
    ) -> str: ...
    async def get_object_url(self, object_name: str, expires_in: int = 3600) -> str: ...
    async def delete_object(self, object_name: str) -> None: ...
